### ISSUE TITLE
Contributors guidelines

### ISSUE THREAD

**Issue by dannysofftie** [Flutterwave/ravepay-nodejs#34]
Would like to contribute to this project, specifically to add TypeScript definitions for existing code base. 

Requesting a few stuffs:
 - Contributors guideline,
 - Code formatting guidelines, an editor config or something similar

**Comment by navicstein** [comment]
@dannysofftie 🙏
Yes I'll love to add typescript definition files, I had already started creating my version before I saw this pull, better still, some naming conventions needs to be followed, maybe in the next version the lib will be completely written in typescript since definitions can be generated automatically

**Comment by dannysofftie** [comment]
Great stuff, I'd love to contribute when you plan to rewrite in typescript.

**Comment by Corvus97** [comment]
Hello @dannysofftie @navicstein,

The Team is really excited to see what you'll add to the repo.

We are working on a contributor's guideline for this project and will be sharing it with the rest of the community before the week runs out.

Remain awesome Guys!
